version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=verceldb
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
  
  